frontpage/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

app_name = 'frontpage' 
urlpatterns = [
    path('', views.home, name='home'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
   
]

record/urls.py
from django.urls import path
from . import views

app_name = 'record' 
urlpatterns = [
    path('create/', views.create_record, name='create_record'),
    path('update/<int:record_id>/', views.update_record, name='update_record'),
    path('complete/<int:record_id>/', views.complete_record, name='complete_record'),
    path('delete/<int:record_id>/', views.delete_record, name='delete_record'),
    path('generate_report/', views.generate_report, name='generate_report'),
    path('', views.record_list, name='record_list'),
]

src/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('record/', include('record.urls')),
    path('', include('frontpage.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  

frontpage/models.py
from django.db import models

# Create your models here.

record/models.py
from django.db import models
from station.models import Station

# Create your models here.
class Record(models.Model):
    # Fields for storing user details and attendance data
    fname = models.CharField(max_length=50)  # First Name
    lname = models.CharField(max_length=50)  # Last Name
    onames = models.CharField(max_length=100, blank=True)  # Other Names (optional)
    
    # Reference to Station model (dropdown-style selection)
    station = models.ForeignKey(Station, on_delete=models.SET_NULL, null=True, blank=True)
    
    time_in = models.DateTimeField(auto_now_add=True)  # Time when the person checks in
    time_out = models.DateTimeField(null=True, blank=True)  # Time when the person checks out
    
    signature = models.ImageField(upload_to='signature/', null=True, blank=True)  # Add this field
    
    def __str__(self):
        return f"{self.fname} {self.lname} - {self.onames} at {self.station.name if self.station else 'Unknown Station'}"

station/models.py
from django.db import models

# Create your models here.

class Station(models.Model):
    name = models.CharField(max_length=100, unique=True)
    def __str__(self):
        return f"{self.name}"

record/forms.py
from django import forms
from .models import Record, Station

class RecordForm(forms.ModelForm):
    class Meta:
        model = Record
        fields = ['fname', 'lname', 'onames', 'station', 'signature']

    signature = forms.CharField(widget=forms.HiddenInput())  # We'll pass the base64 signature here

frontpage/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'frontpage/home.html')

record/views.py
import base64
import os
import uuid
from datetime import datetime
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.core.files.base import ContentFile
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.utils import timezone
from django.http import HttpResponse
import csv

from .models import Record
from .forms import RecordForm


@login_required
def create_record(request):
    if request.method == 'POST':
        form = RecordForm(request.POST)
        signature_data = request.POST.get('signature')
      
        if form.is_valid() and signature_data:
            print("form is valid")
            
            # Generate a unique filename using UUID
            unique_filename = f"signature_{uuid.uuid4().hex}.png"
            
            # Extract base64 signature (strip the header if present)
            if signature_data.startswith('data:image/png;base64,'):
                signature_data = signature_data.split('data:image/png;base64,')[1]
            
            # Convert base64 to image
            signature_image = ContentFile(base64.b64decode(signature_data), name=unique_filename)
            
            # Save the image to the 'signature' directory (Django will handle saving it in MEDIA_ROOT)
            form.instance.signature.save(unique_filename, signature_image)
            print("saved the image to the file")
            
            # Save the form with the signature image URL
            form.save()

            return redirect('record_list')  # Redirect to the record list page
        else:
            print(form.errors)
    else:
        form = RecordForm()

    return render(request, 'record/create_record.html', {'form': form})

@login_required
def update_record(request, record_id):
    record = get_object_or_404(Record, pk=record_id)
    if request.method == 'POST':
        form = RecordForm(request.POST, instance=record)
        signature_data = request.POST.get('signature')

        if form.is_valid():
            # If a new signature is provided, update it
            if signature_data:
                unique_filename = f"signature_{uuid.uuid4().hex}.png"
                if signature_data.startswith('data:image/png;base64,'):
                    signature_data = signature_data.split('data:image/png;base64,')[1]
                signature_image = ContentFile(base64.b64decode(signature_data), name=unique_filename)
                record.signature.save(unique_filename, signature_image)

            form.save()
            return redirect('record_list')  # Redirect after saving the form
        else:
            print(form.errors)
    else:
        form = RecordForm(instance=record)

    return render(request, 'record/update_record.html', {'form': form, 'record': record})

@login_required
def record_list(request):
    records = Record.objects.all()
    return render(request, 'record/record_list.html', {'records': records})

@login_required
def complete_record(request, record_id): 
    record = get_object_or_404(Record, pk=record_id)
    if record:
        record.time_out = timezone.now()  # Set the current time as time_out
        record.save()
        messages.success(request, 'Attendance marked as completed successfully.')
        return redirect('record_list') 
    else:
        messages.error(request, 'Record not found.')
        return redirect('record_list')

@login_required
def delete_record(request, record_id):
    record = get_object_or_404(Record, pk=record_id)
    if record:
        record.delete()
        messages.success(request, 'Record deleted successfully.')
        return redirect('record_list') 
    else:
        messages.error(request, 'Record not found.')
        return redirect('record_list')

@login_required
def generate_report(request):
    # Get the start and end date from the request parameters
    start_date = request.GET.get('start_date', '')
    end_date = request.GET.get('end_date', '')

    if start_date and end_date:
        # Convert string to datetime
        start_date = datetime.strptime(start_date, '%Y-%m-%d')
        end_date = datetime.strptime(end_date, '%Y-%m-%d')
        records = Record.objects.filter(time_in__range=[start_date, end_date])
       
    else:
        records = Record.objects.all()
    if not records:
        messages.error(request, "No records found for the given date range.")
        return redirect('record_list')

    filename = f'{start_date.strftime("%Y_%m_%d")}_to_{end_date.strftime("%Y_%m_%d")}_attendance_report.csv'

    # Create an HTTP response with CSV content type
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = f'attachment; filename="{filename}"'

    # Create the CSV writer and write the header
    writer = csv.writer(response)
    writer.writerow(['First Name', 'Last Name', 'Station', 'Time In', 'Time Out'])

    # Write records to CSV
    for record in records:
        writer.writerow([record.fname, record.lname, record.station.name, record.time_in, record.time_out])

    return response

station/views.py
from django.shortcuts import render

# Create your views here.

frontpage/templates/frontpage/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Attendo - Attendance App</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
</head>
<body>

  <section class="hero bg-primary text-white text-center py-5">
    <div class="container">
      <h1 class="display-4 fw-bold">Welcome to Attendo</h1>
      <p class="lead">The easiest and most efficient way to track attendance!</p>
      </div>
  </section>

  <section id="features" class="py-5">
    <div class="container text-center">
        <div class="row">
            <div class="col-md-12">
               <img src="{% static 'img/3902762.jpg' %}">
            </div>
        </div>
    </div> 
  </section>

  <section id="download" class="bg-light py-5 text-center">
    <div class="container">
      <h2 class="mb-4">Get Started with Attendo Today!</h2>
      <a href="{% url 'frontpage:login' %}" class="btn btn-primary btn-lg">
        <i class="fas fa-download"></i> Login
      </a>
    </div>
  </section>

  <footer class="bg-dark text-white text-center py-3" style="position: fixed; bottom: 0; width: 100%; z-index: 1000;">
    <p>&copy; 2024 Attendo. All rights reserved.</p>
  </footer>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

record/templates/record/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Attendance Management{% endblock %}</title>
    
    <!-- Bootstrap 5 CDN -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    
    <!-- Optional: Custom Styles (if any) -->
    <style>
        .container {
            margin-top: 20px;
        }
    </style>

    {% block extra_head %}{% endblock %}
</head>
<body>
    <!-- Navigation Bar -->
   <!-- Navigation Bar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Attendance System</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'record:record_list' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'record:create_record' %}">Create Record</a>
                </li>
            </ul>
            <!-- Align user name and logout button to the right -->
            <ul class="navbar-nav ms-auto d-flex align-items-center">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <span class="navbar-text">Welcome, {{ user.username }}!</span>
                    </li>
                    <li class="nav-item">
                        <form method="POST" action="{% url 'frontpage:logout' %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-outline-danger ms-2">Logout</button>
                        </form>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>


    <div class="row">
        <div class="col-md-12">
            {% if messages %}
                <div class="alert alert-info">
                    {% for message in messages %}
                        <p>{{ message }}</p>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
    </div>
    <!-- Main Content -->
    <div class="container">
        {% block content %}{% endblock %}
    </div>

    <!-- Bootstrap JS and Popper.js -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"></script>

    {% block extra_scripts %}{% endblock %}
</body>
</html>

record/templates/record/create_record.html
{% extends 'record/base.html' %}

{% block title %}Create Attendance Record{% endblock %}

{% block content %}
<h2>Create Attendance Record</h2>

<form method="POST" enctype="multipart/form-data" id="signatureForm">
    {% csrf_token %}    
    <!-- First Name Field -->
    <div class="mb-3">
        <label for="{{ form.fname.id_for_label }}" class="form-label">Enter First Name</label>
        <input type="text" class="form-control" id="{{ form.fname.id_for_label }}" name="{{ form.fname.name }}" value="{{ form.fname.value|default_if_none:'' }}" aria-describedby="{{ form.fname.id_for_label }}-help">
    </div>
    <!-- Last Name Field -->
    <div class="mb-3">
        <label for="{{ form.lname.id_for_label }}" class="form-label">Enter Last Name</label>
        <input type="text" class="form-control" id="{{ form.lname.id_for_label }}" name="{{ form.lname.name }}" value="{{ form.lname.value|default_if_none:'' }}" aria-describedby="{{ form.lname.id_for_label }}-help">
    </div> 
    <!-- Other Names Field -->
    <div class="mb-3">
        <label for="{{ form.onames.id_for_label }}" class="form-label">Enter Other Names</label>
        <input type="text" class="form-control" id="{{ form.onames.id_for_label }}" name="{{ form.onames.name }}" value="{{ form.onames.value|default_if_none:'' }}" aria-describedby="{{ form.onames.id_for_label }}-help">
    </div>  
    <!-- Station Dropdown -->
    <div class="mb-3">         
        <label for="{{ form.station.id_for_label }}" class="form-label">Select the station</label>
        <select id="{{ form.station.id_for_label }}" class="form-select" name="{{ form.station.name }}">
        
            {% for choice in form.station.field.choices %}
                <option value="{{ choice.0 }}" {% if choice.0 == form.station.value %} selected {% endif %}>{{ choice.1 }}</option>
            {% endfor %}
        </select>       
    </div>

    <!-- Signature Pad -->
    <div class="mb-3">
        <label for="signature-pad" class="form-label"><b>Signature</b></label>       
    </div>
    <div class="mb-3">      
        <canvas id="signature-pad" width="400" height="200" style="border: 2px solid green;"></canvas>
    </div>

    <button type="button" id="clear" class="btn btn-danger">Clear</button>
    <br><br>
    <button type="submit" class="btn btn-primary">Submit</button>
    
    <!-- Hidden field for the signature data -->
    <input type="hidden" name="signature" id="signatureInput">
</form>

{% endblock %}

{% block extra_scripts %}
    <!-- Correct CDN for SignaturePad -->
    <script src="https://cdn.jsdelivr.net/npm/signature_pad@4.0.0/dist/signature_pad.umd.min.js"></script>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            // Get references to elements
            var canvas = document.getElementById('signature-pad');
            var clearButton = document.getElementById('clear');
            var signatureForm = document.getElementById('signatureForm');
            var signatureInput = document.getElementById('signatureInput');
            var signaturePad = new SignaturePad(canvas);

            // Clear the signature pad when the "Clear" button is clicked
            clearButton.addEventListener('click', function() {
                signaturePad.clear();
            });

            // Handle form submission
            signatureForm.addEventListener('submit', function(event) {
                if (!signaturePad.isEmpty()) {
                    // If signature is not empty, set the hidden field with the base64 data URL
                    signatureInput.value = signaturePad.toDataURL();
                } else {
                    // If the signature is empty, show an alert and prevent form submission
                    alert('Please provide a signature.');
                    event.preventDefault();
                }
            });
        });
    </script>
{% endblock %}

record/templates/record/record_list.html
{% extends 'record/base.html' %}

{% block title %}Attendance Records{% endblock %}

{% block content %}
<h2>Attendance Records</h2>
<form method="GET" action="{% url 'record:generate_report' %}">
    <input type="date" name="start_date" required>
    <input type="date" name="end_date" required>
    <button type="submit">Generate Report</button>
</form>

<table class="table table-striped table-sm table-responsive">
    <thead class="table-light">
        <tr>
            <th>Name</th>          
            <th>Station</th>            
            <th>Time In</th>
            <th>Time Out</th>
            <th>Signature</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for record in records %}
        <tr>
            <td>{{ record.lname }} {{ record.fname }} {{ record.onames }}</td>          
            <td>{{ record.station.name }}</td>          
            <td>{{ record.time_in }}</td>
            <td>{{ record.time_out }}</td>
            <td><img src="{{ record.signature.url }}" alt="Signature" width="100"></td>
            <td>
                {% if not record.time_out %}
                <a href="{% url 'record:update_record' record.pk %}" class="btn btn-secondary btn-sm">Edit</a>
                <a href="{% url 'record:delete_record' record.pk %}" class="btn btn-danger btn-sm">Delete</a>
                <a href="{% url 'record:complete_record' record.pk %}" class="btn btn-success btn-sm">Done</a>                
                {% endif %}
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="8" class="text-center">No records found.</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

record/templates/record/update_record.html
{% extends 'record/base.html' %}

{% block title %}Update Attendance Record{% endblock %}

{% block content %}
<h2>Update Attendance Record</h2>

<form method="POST" enctype="multipart/form-data" id="signatureForm">
    {% csrf_token %}
    <!-- First Name Field -->
    <div class="mb-3">
        <label for="{{ form.fname.id_for_label }}" class="form-label">First Name</label>
        <input type="text" class="form-control" id="{{ form.fname.id_for_label }}" name="{{ form.fname.name }}" value="{{ form.fname.value|default_if_none:'' }}" aria-describedby="{{ form.fname.id_for_label }}-help">
    </div>

    <!-- Last Name Field -->
    <div class="mb-3">
        <label for="{{ form.lname.id_for_label }}" class="form-label">Last Name</label>
        <input type="text" class="form-control" id="{{ form.lname.id_for_label }}" name="{{ form.lname.name }}" value="{{ form.lname.value|default_if_none:'' }}" aria-describedby="{{ form.lname.id_for_label }}-help">
    </div>

    <!-- Other Names Field -->
    <div class="mb-3">
        <label for="{{ form.onames.id_for_label }}" class="form-label">Other Names</label>
        <input type="text" class="form-control" id="{{ form.onames.id_for_label }}" name="{{ form.onames.name }}" value="{{ form.onames.value|default_if_none:'' }}" aria-describedby="{{ form.onames.id_for_label }}-help">
    </div>

    <!-- Station Dropdown -->
    <div class="mb-3">
        <label for="{{ form.station.id_for_label }}" class="form-label">Select the station</label>
        <select id="{{ form.station.id_for_label }}" class="form-select" name="{{ form.station.name }}">
            {% for choice in form.station.field.choices %}
                <option value="{{ choice.0 }}" {% if choice.0 == form.station.value %} selected {% endif %}>{{ choice.1 }}</option>
            {% endfor %}
        </select>
    </div>

    <!-- Signature Pad -->
    <div class="mb-3">
        <label for="signature-pad" class="form-label"><b>Signature</b></label>
    </div>
    <div class="mb-3">
        <canvas id="signature-pad" width="400" height="200" style="border: 2px solid green;"></canvas>
    </div>

    <button type="button" id="clear" class="btn btn-danger">Clear</button>
    <br><br>
    <button type="submit" class="btn btn-primary">Submit</button>

    <!-- Hidden field for the signature data -->
    <input type="hidden" name="signature" id="signatureInput">
</form>

{% endblock %}

{% block extra_scripts %}
    <!-- Correct CDN for SignaturePad -->
    <script src="https://cdn.jsdelivr.net/npm/signature_pad@4.0.0/dist/signature_pad.umd.min.js"></script>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            var canvas = document.getElementById('signature-pad');
            var clearButton = document.getElementById('clear');
            var signatureForm = document.getElementById('signatureForm');
            var signatureInput = document.getElementById('signatureInput');
            var signaturePad = new SignaturePad(canvas);

            clearButton.addEventListener('click', function() {
                signaturePad.clear();
            });

            signatureForm.addEventListener('submit', function(event) {
                if (!signaturePad.isEmpty()) {
                    signatureInput.value = signaturePad.toDataURL();
                } else {
                    alert('Please provide a signature.');
                    event.preventDefault();
                }
            });
        });
    </script>
{% endblock %}